# Copyright 2026 atframework
ignore:
  - "**/sample/**"
  - "**/test/**"
  - "**/tools/**"
  - "**/build_jobs_coverage/CMakeFiles/**"
  - "**/docs/**"
  - "**/include/libatbus_protocol.pb.h"
  - "**/src/libatbus_protocol.pb.cc"
  - "**/third_party/**"
  - "**/atframework/**"